### ISSUE TITLE
Reverb not working with pre-existing config files in 1.18

### ISSUE THREAD

**Issue by Placeblock** [vlad2305m/Sound-Physics-Fabric#16]
The Title explains it very well,
The mod doesn't work, but if i delete the config file it does.
Then, When i restart Minecraft again, it doesnt work again

Doesn't work
Delete config and restart
Work
Restart
Doesn't work
Delete config and restart
Work
...

Minecraft Version 1.18

Sorry for my bad English...

Have a great day :)

**Comment by thedocruby** [comment]
I think the wording threw me off, maybe change the title to "Reverb not working with pre-existing config files in 1.18"

**Comment by Placeblock** [comment]
> I think the wording threw me off, maybe change the title to "Reverb not working with pre-existing config files in 1.18" ?

does make a lot more sense now :D

**Comment by vlad2305m** [comment]
Hope v3.1 works for you )

**Comment by GlowingUmbreon** [comment]
> Hope v3.1 works for you )

yep, fixed

**Comment by Placeblock** [comment]
For me it is still not working...

I enabled logging and everything works fine (i think)
[latest.txt](https://github.com/vlad2305m/Sound-Physics-Fabric/files/7656614/latest.txt)

I had thought about whether it doesn't work because some kind of speaker problem, but i still hear the normal minecraft sounds so this cant be the problem...
 you mentioned already that the with the default config you just nearly hear nothing, but i thought with the new version the default config from thedocruby was implemented...

**Comment by vlad2305m** [comment]
@Placeblock 
1) Did you delete your old config file?
2) Do you see rays towards you if you enable debug particles? (Without logging)
3) If it still doesn't work, pack me your mods folder and the SP confg file.

**Comment by Placeblock** [comment]
Some kind of good news: i can see the raytracing particles, even tho nothing comes trough my speakers[mods.zip]

Here is my config (txt because i cant send json5 files)
[sound_physics.txt](https://github.com/vlad2305m/Sound-Physics-Fabric/files/7656662/sound_physics.txt)

(https://github.com/vlad2305m/Sound-Physics-Fabric/files/7656660/mods.zip)
Here are all my mods

i tried removing all mods except for cloth config, modmenu and soundphysics and it is still not working...

**Comment by vlad2305m** [comment]
If it worked in 1.17, I have a guess

**Comment by Placeblock** [comment]
i will try if it works in 1.17 i haven't tried it... do i have to use a different version?

**Comment by vlad2305m** [comment]
> i will try if it works in 1.17 i haven't tried it... do i have to use a different version?

Yes, 2.something

**Comment by vlad2305m** [comment]
So, now it definetely should work (v3.2)

**Comment by Placeblock** [comment]
I just tried v3.2 which you included in the 3.1 release and... now i don't hear anything except for GUI button clicks, sometimes even button clicks don't have any sound, its random i think...
i noticed something weird: in v3.2 the Raytracing particles are strange... they are where they shouldn't and start from locations where no mob is located

btw thank you for helping me all the time!

**Comment by vlad2305m** [comment]
OK I finally managed to get this issue. I see now.

**Comment by Placeblock** [comment]
I must say it again: Thank you so much for your help, i appreciate it very much.
we desperately need more people like you ;)

**Comment by vlad2305m** [comment]
I'm just procrastinating )

**Comment by vlad2305m** [comment]
I got it to work

**Comment by vlad2305m** [comment]
v4.0 Yea, I had to change the config for it to work again

**Comment by Placeblock** [comment]
Thank you very very much its working!!!
