### ISSUE TITLE
Reverb not working in 1.18

### ISSUE THREAD

**Issue by thedocruby** [vlad2305m/Sound-Physics-Fabric#17]
Reverb doesn't appear to have any effect in 1.18 (3.0.0), even with the same config settings that work in 1.17 (2.1.0).
IDK what else to say, but if you want me to check something or do some more digging then just say so.

oh also occlusion appears to work.

**Comment by Placeblock** [comment]
Is it working if you delete the sound_physics.json5 config file in the config folder in minecraft folder?
i've the same problem and it works everytime i delete the config and restart minecraft, but if i restart it again its broken again...
#16

**Comment by thedocruby** [comment]
@Placeblock huh, i didn't think these issues were related. I'll try and see if it works. If so i will close this issue
