### ISSUE TITLE
Config rework

### ISSUE THREAD

**Issue by thedocruby** [vlad2305m/Sound-Physics-Fabric#22]
This PR aims to do a number of things to improve the config:
- [x] Add translations for the `enum` values in lang file
- [ ] Add translatable tooltips to the config screen
- [ ] Add more basic presets with different purposes
- [ ] Remove the need for `reloadReverb` using the config save event in cloth configthat I read about yesterday and can't seem to find any documentation about it today (including where I originally read it)

I also submitted a request for shedaniel to add the ability for us to access the traditional style of drop-down menu from the Auto Config API, it is not currently accessible to us even though it is part of Cloth Config. This will be much better than the current style of "suggestive search" dropdown, and will remove the need for all of the presets to be listed in the tooltip. I also requested her to enable the dropdowns to change width based on the width of their content, which is something that other configs do and is very useful. Also, about the cloth config file save event that I read about yesterday? I can't seem to find any documentation about it anywhere (including where I originally read about it).

EDIT: After nearly 2.5 hours of searching, I still can't find the documentation for the cloth config file save event, or a lot of other things. Come to think of it, i only knew that the dropdowns even existed in Auto Config because they were already in this mod, since there is zero documentation about them in the wiki. Cloth Config is looking more and more like a very poorly maintained and documented API, which is very frustrating. I'm starting to think it might be a better idea to use something like SpruceUI, or just try to make our own config screen like Iris is doing.

**Comment by thedocruby** [comment]
Moved tracking to Projects

**Comment by vlad2305m** [comment]
I looked at some options for changing config api, but I only found very forge-like ones (with very long field builders). The reason why I chose this api is the jankson serializer, that can save almost any data structure to a file, while autoconfig nicely creates a screen for it.
If you have any on mind, please tell (spruce is 1.17)
In the worst case I can make very soft mixins to fix Cloth.
