### ISSUE TITLE
Publish version 0.4.1

### ISSUE THREAD

**Issue by thedocruby** [vlad2305m/Sound-Physics-Fabric#27]
@vlad2305m I didn't know how else to contact you. Maybe you could share your discord so i can contact you in the future? Anyway, v0.4.1 is done. Rough changelog:

* Added basic presets
* Added user-friendly preset names
* Moved to 3-part versioning
* Fixed some bugs with tooltips in the GUI

**Comment by vlad2305m** [comment]
vlad2305m@6151
Just please only push when you are finished with a version so that I can quickly see all the changes to the code ) (or rarely, if it takes a lot of time)

**Comment by vlad2305m** [comment]
Also give me your Curseforge username so that you can publish there as well

I increase base number whenever the config becomes incompatible, so there is no need for 3-digit, but ok.

**Comment by vlad2305m** [comment]
Please add .gitignore to .gitignore

**Comment by thedocruby** [comment]
> Just please only push when you are finished with a version so that I can quickly see all the changes to the code ) (or rarely, if it takes a lot of time)

Yeah, I was pretty sloppy wasn't I? I'll try to be more organized going forward.

My curseforge username is also thedocruby

Also question, do i need to publish the mod to maven or something? I wasn't sure so I didn't.

>Please add .gitignore to .gitignore

I didn't think that was even physically possible, but if it is i will definitely do so.

**Comment by vlad2305m** [comment]
Actually I have a workaround for the fist one, so I am fine

I am very bad (just copying from others) with maven/loom/gradle so if you find a way how to publish to maven (and retrieve it from there), it may be useful for somebody (doing voicechat compatibility, for example)
