### ISSUE TITLE
Cloth Config not sufficient?

### ISSUE THREAD

**Issue by thedocruby** [vlad2305m/Sound-Physics-Fabric#28]
It is becoming more and more apparent that Cloth Config API and Auto Config 1u are not well enough maintained and documented to provide for this mod's growing feature set. It is possible that we will have to move to a new config gui api, such as Spruce UI, or even build our config from scratch. If the issues are not resolved by shedaniel before the new year, then I will start work on a new config screen independent of Cloth Config and Auto Config.

**Comment by vlad2305m** [comment]
You mean collapsibility? Explain.

**Comment by thedocruby** [comment]
@vlad2305m 
My process of constantly encountering limitations of ClothConfig and AutoConfig is sloppily outlined in this issue:
https://github.com/vlad2305m/Sound-Physics-Fabric/issues/22
