### ISSUE TITLE
No Nether Reverb

### ISSUE THREAD

**Issue by JasonHorkles** [vlad2305m/Sound-Physics-Fabric#35]
It would be awesome if the Nether had reverb but it just doesn't seem to at all

**Comment by thedocruby** [comment]
Please provide more information about your situation and any other mods you may be using. Are you using Immersive Portals? This has been known to cause issues.

**Comment by JasonHorkles** [comment]
Here's my current mods list (having switched to the remastered fork it seems to work fine in the Nether, I should note)
![image](https://user-images.githubusercontent.com/51760372/145854058-09c178d6-3a94-47b6-a3d1-69ec805c9a54.png)
Preset and everything was default, so not sure why it refused to do anything in the Nether
![image](https://user-images.githubusercontent.com/51760372/145854253-8da41532-1e10-43b9-9c79-1836914030bc.png)
However, this was with SoundPhysics 0.4.2 IIRC so it'd need more testing

**Comment by thedocruby** [comment]
Looks like you're using sound physics remastered, a fork of an older version of this mod without the latest features. Try submitting a bug report on [their GitHub](https://github.com/henkelmax/sound-physics-remastered).

**Comment by JasonHorkles** [comment]
Like I mentioned:
> having switched to the remastered fork it seems to work fine in the Nether, I should note

**Comment by thedocruby** [comment]
Ah I see, thank you. Most likely a duplicate of #37 , Can you confirm?
