### ISSUE TITLE
No In-game Sound when Rendering is Enabled

### ISSUE THREAD

**Issue by Hyporeal** [vlad2305m/Sound-Physics-Fabric#36]
I've used this mod in 1.17.1. I'm not sure what the issue is here in 1.18.

**Comment by thedocruby** [comment]
Please provide more information about your situation. What version of the mod are you using? What version of Fabric and Minecraft? What version of Cloth Config? What other mods are you using? What have you done to test this? Any information you can provide is greatly appreciated.

**Comment by SleepyTonia** [comment]
I had this issue with the previous (0.4.2) version in Minecraft 1.18. Any positional sounds stopped working with no warning. I had to disable rendering and then leave the world to reload it if I wanted sound to work as normal again.

**Comment by thedocruby** [comment]
This occurred for me occasionally in a development testing version for release 0.5.0, but I believe @vlad2305m did some coding magic to prevent this in the newest version. Can you try with release 0.5.0?

**Comment by vlad2305m** [comment]
@thedocruby I'm not sure it has been fixed.
What rendering? How occasionally? (is there a pattern?)
Where is the log? (It should be absolutely spammed with "Sound engine crashed: ...")
How to reproduce the bug?

**Comment by SleepyTonia** [comment]
I hate to say this, but I went back, installed 0.4.2 with 1.18, same accompanying mods and somehow couldn't reproduce what I'd experienced last time.

**Comment by thedocruby** [comment]
Thanks for the update!

**Comment by vlad2305m** [comment]
For me various things are crushing the windows mixer, so each time I run the script:
