### ISSUE TITLE
No small reverb

### ISSUE THREAD

**Issue by Slayer66633** [vlad2305m/Sound-Physics-Fabric#48]
Hello.  I noticed that in small rooms there is no muffled reverb like in the original version from SonicEther.  In addition, I hear a strong echo when I dig a two-block tunnel like I'm in a huge cave, is this a bug?  The ported version is quite different from the original.  "sorry for my bad english"

**Comment by DearFox** [comment]
Weird, I don't have an echo effect at all on 1.18.1
I'm using the latest version of the mod at the moment (compatible with 1.18.1)
The rest of the effects seem to be working (weaker sound behind obstacles)

**Comment by thedocruby** [comment]
These are both probably because of a bug in 0.5.4 that has been fixed in commit f6c4fdcfc155a668bcd2ec1a8baabe63643cf7bc
